const columnSchema = [
    {
      Title: "CRISIS",
      sorting: true,
      grouping: true,
      rotate: false,
      visibility: false,
    },
    {
      Title: "EDITION",
      sorting: true,
      grouping: true,
      rotate: false,
      visibility: false,
    },
    {
      Title: "YEAR",
      sorting: true,
      grouping: true,
      rotate: false,
      visibility: false,
    },
    {
      Title: "COUNTRY",
      sorting: true,
      grouping: true,
      rotate: false,
      visibility: false,
    },
    {
      Title: "CASE STUDY",
      sorting: true,
      grouping: true,
      rotate: false,
      visibility: false,
    },
    {
      Title: "Accessibility / Disability Inclusion",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Adaptability (of shelter solutions)",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Advocacy",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Cash and Market-based approaches",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Community engagement",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Coordination and partnerships",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Cost effectiveness",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Coverage and scale",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Cultural appropriateness of shelter solutions",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Disaster Risk Reduction",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Durability of shelter solutions",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Environmental sustainability",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Flexibility of the organization / project",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "GBV risk mitigation",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Gender mainstreaming / Women’s empowerment",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Geographic Targeting (project locations)",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Habitability / Comfort",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Health",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Integrated programming / Multi-sectoral approaches",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Links with recovery / wider impacts / durable solutions",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Livelihoods / employment opportunities",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Local authority / Government engagement",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Local construction techniques / capacity / materials",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Local private sector engagement",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Location and settlement planning",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Market-based approaches",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Monitoring and Evaluation",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Occupants’ satisfaction",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Organizational capacity / Preparedness",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Procurement and logistics",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Project planning",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Protection mainstreaming / risk mitigation",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Security of Tenure / HLP",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Settlements approach",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Social Cohesion / Community stabilization / Resilience",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Socio-Technical Assistance quality",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Targeting of assistance (beneficiary selection)",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Team composition / Staffing",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
    {
      Title: "Timeliness of the assistance",
      sorting: true,
      grouping: false,
      rotate: true,
      visibility: true,
    },
  ];
  export default columnSchema