const columnSchema = [
  {
    Title: "CRISIS",
    sorting: true,
    grouping: true,
    rotate: false,
    visibility: false,
    tooltip: true,
  },
  {
    Title: "EDITION",
    sorting: true,
    grouping: true,
    rotate: false,
    visibility: false,
    tooltip: true,
  },
  {
    Title: "YEAR",
    sorting: true,
    grouping: true,
    rotate: false,
    visibility: false,
    tooltip: true,
  },
  {
    Title: "COUNTRY",
    sorting: true,
    grouping: true,
    rotate: false,
    visibility: false,
    tooltip: true,
  },
  {
    Title: "CASE STUDY",
    sorting: true,
    grouping: false,
    rotate: false,
    visibility: false,
    tooltip: true,
  },
  {
    Title: "Accessibility / Disability Inclusion",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Adaptability (of shelter solutions)",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Advocacy",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Cash and Market-based approaches",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Community engagement",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Coordination and partnerships",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Cost effectiveness",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Coverage and scale",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Cultural appropriateness of shelter solutions",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Disaster Risk Reduction",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Durability of shelter solutions",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Environmental sustainability",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Flexibility of the organization / project",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "GBV risk mitigation",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Gender mainstreaming / Women’s empowerment",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Geographic Targeting (project locations)",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Habitability / Comfort",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Health",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Integrated programming / Multi-sectoral approaches",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Links with recovery / wider impacts / durable solutions",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Livelihoods / employment opportunities",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Local authority / Government engagement",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Local construction techniques / capacity / materials",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Local private sector engagement",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Location and settlement planning",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Market-based approaches",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Monitoring and Evaluation",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Occupants’ satisfaction",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Organizational capacity / Preparedness",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Procurement and logistics",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Project planning",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Protection mainstreaming / risk mitigation",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Security of Tenure / HLP",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Settlements approach",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Social Cohesion / Community stabilization / Resilience",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Socio-Technical Assistance quality",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Targeting of assistance (beneficiary selection)",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Team composition / Staffing",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
  {
    Title: "Timeliness of the assistance",
    sorting: true,
    grouping: false,
    rotate: true,
    visibility: true,
    tooltip: false,
  },
];
export default columnSchema;



